---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: mailhog-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mailhog
  template:
    metadata:
      labels:
        app: mailhog
    spec:
      containers:
      - name: mailhog
        image: mailhog/mailhog
        ports:
        - containerPort: 1025
        - containerPort: 8025
